In [2]:
!pip install pandas 

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 184.2 kB/s eta 0:00:57
   - -------------------------------------- 0.5/11.0 MB 184.2 kB/s eta 0:00:57
   -- ------------------------------------- 0.8/11.0 MB 305.6 kB/s eta 0:00:34
   --- ------------------------------------ 1.0/11.0 MB 404.9 kB/s eta 0:00:25
   ---- ----------------------------------- 1.3/11.0 M

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('meets.csv')

In [3]:
df.head()

MeetID        MeetPath Federation        Date MeetCountry MeetState  \
0       0  365strong/1601  365Strong  2016-10-29         USA        NC   
1       1  365strong/1602  365Strong  2016-11-19         USA        MO   
2       2  365strong/1603  365Strong  2016-07-09         USA        NC   
3       3  365strong/1604  365Strong  2016-06-11         USA        SC   
4       4  365strong/1605  365Strong  2016-04-10         USA        SC   

    MeetTown                                           MeetName  
0  Charlotte  2016 Junior & Senior National Powerlifting Cha...  
1      Ozark                  Thanksgiving Powerlifting Classic  
2  Charlotte                             Charlotte Europa Games  
3  Rock Hill                   Carolina Cup Push Pull Challenge  
4  Rock Hill                              Eastern USA Challenge

In [4]:
df.loc[:,'Federation']

0       365Strong
1       365Strong
2       365Strong
3       365Strong
4       365Strong
          ...    
8477          XPC
8478          XPC
8479          XPC
8480          XPC
8481          XPC
Name: Federation, Length: 8482, dtype: object

In [5]:
df.iloc[0:10,0:4]

MeetID        MeetPath Federation        Date
0       0  365strong/1601  365Strong  2016-10-29
1       1  365strong/1602  365Strong  2016-11-19
2       2  365strong/1603  365Strong  2016-07-09
3       3  365strong/1604  365Strong  2016-06-11
4       4  365strong/1605  365Strong  2016-04-10
5       5  365strong/1701  365Strong  2017-04-22
6       6  365strong/1702  365Strong  2017-01-21
7       7  365strong/1703  365Strong  2017-06-10
8       8  365strong/1704  365Strong  2017-07-15
9       9  365strong/1705  365Strong  2017-08-12

In [6]:
df.iloc[0:10,0:4]

MeetID        MeetPath Federation        Date
0       0  365strong/1601  365Strong  2016-10-29
1       1  365strong/1602  365Strong  2016-11-19
2       2  365strong/1603  365Strong  2016-07-09
3       3  365strong/1604  365Strong  2016-06-11
4       4  365strong/1605  365Strong  2016-04-10
5       5  365strong/1701  365Strong  2017-04-22
6       6  365strong/1702  365Strong  2017-01-21
7       7  365strong/1703  365Strong  2017-06-10
8       8  365strong/1704  365Strong  2017-07-15
9       9  365strong/1705  365Strong  2017-08-12

In [7]:
df.head(1)

MeetID        MeetPath Federation        Date MeetCountry MeetState  \
0       0  365strong/1601  365Strong  2016-10-29         USA        NC   

    MeetTown                                           MeetName  
0  Charlotte  2016 Junior & Senior National Powerlifting Cha...

In [8]:
df.loc[150:200,['Date','MeetCountry']]

Date  MeetCountry
150  2015-08-02           UK
151  2015-02-07           UK
152  2016-10-01           UK
153  2016-09-17           UK
154  2016-01-23           UK
155  2016-03-27           UK
156  2017-01-15           UK
157  2017-01-16           UK
158  2017-02-25           UK
159  2017-03-11           UK
160  2017-03-25           UK
161  2017-07-29           UK
162  2017-10-21           UK
163  2017-11-04           UK
164  2017-11-25           UK
165  2017-12-09           UK
166  2018-01-21           UK
167  2018-01-20           UK
168  2017-11-11      England
169  2017-06-03    Australia
170  2017-05-21    Australia
171  2017-04-30    Australia
172  2017-05-20    Australia
173  2017-04-25    Australia
174  2017-10-07    Australia
175  2005-09-05      England
176  2005-09-05      England
177  2007-12-05  New Zealand
178  2007-12-05  New Zealand
179  2009-12-09        India
180  2009-12-09        India
181  2011-12-16      England
182  2013-12-05  New Zealand
183  2013-12-04  New Zealand
184  2013-12-05  New Zealand
185  2013-12-06  New Zealand
186  2013-12-05  New Zealand
187  2013-12-05  New Zealand
188  2013-12-06  New Zealand
189  2013-12-04  New Zealand
190  2015-12-01       Canada
191  2006-12-02       Canada
192  2015-11-20       Canada
193  2015-11-14       Canada
194  2015-11-07       Canada
195  2015-06-27       Canada
196  2016-06-26       Canada
197  2016-12-17       Canada
198  2016-12-10       Canada
199  2016-07-10       Canada
200  2016-01-30       Canada

In [9]:
df.iloc[150:200,3:5]

Date  MeetCountry
150  2015-08-02           UK
151  2015-02-07           UK
152  2016-10-01           UK
153  2016-09-17           UK
154  2016-01-23           UK
155  2016-03-27           UK
156  2017-01-15           UK
157  2017-01-16           UK
158  2017-02-25           UK
159  2017-03-11           UK
160  2017-03-25           UK
161  2017-07-29           UK
162  2017-10-21           UK
163  2017-11-04           UK
164  2017-11-25           UK
165  2017-12-09           UK
166  2018-01-21           UK
167  2018-01-20           UK
168  2017-11-11      England
169  2017-06-03    Australia
170  2017-05-21    Australia
171  2017-04-30    Australia
172  2017-05-20    Australia
173  2017-04-25    Australia
174  2017-10-07    Australia
175  2005-09-05      England
176  2005-09-05      England
177  2007-12-05  New Zealand
178  2007-12-05  New Zealand
179  2009-12-09        India
180  2009-12-09        India
181  2011-12-16      England
182  2013-12-05  New Zealand
183  2013-12-04  New Zealand
184  2013-12-05  New Zealand
185  2013-12-06  New Zealand
186  2013-12-05  New Zealand
187  2013-12-05  New Zealand
188  2013-12-06  New Zealand
189  2013-12-04  New Zealand
190  2015-12-01       Canada
191  2006-12-02       Canada
192  2015-11-20       Canada
193  2015-11-14       Canada
194  2015-11-07       Canada
195  2015-06-27       Canada
196  2016-06-26       Canada
197  2016-12-17       Canada
198  2016-12-10       Canada
199  2016-07-10       Canada

In [10]:
mask=df['MeetCountry']=='UK'
df[mask]

MeetID     MeetPath Federation        Date MeetCountry MeetState  \
137      137      bp/1401         BP  2014-10-04          UK       NaN   
138      138      bp/1402         BP  2014-07-12          UK       NaN   
139      139      bp/1403         BP  2014-03-16          UK       NaN   
140      140      bp/1404         BP  2014-03-15          UK       NaN   
141      141      bp/1405         BP  2014-01-15          UK       NaN   
142      142      bp/1406         BP  2014-09-20          UK       NaN   
143      143      bp/1407         BP  2014-11-29          UK       NaN   
144      144      bp/1501         BP  2015-10-24          UK       NaN   
145      145      bp/1502         BP  2015-10-03          UK       NaN   
146      146      bp/1503         BP  2015-09-19          UK       NaN   
147      147      bp/1504         BP  2015-10-31          UK       NaN   
148      148      bp/1505         BP  2015-11-04          UK       NaN   
149      149      bp/1506         BP  2015-07-03          UK       NaN   
150      150      bp/1507         BP  2015-08-02          UK       NaN   
151      151      bp/1508         BP  2015-02-07          UK       NaN   
152      152      bp/1601         BP  2016-10-01          UK       NaN   
153      153      bp/1602         BP  2016-09-17          UK       NaN   
154      154      bp/1603         BP  2016-01-23          UK       NaN   
155      155      bp/1604         BP  2016-03-27          UK       NaN   
156      156      bp/1701         BP  2017-01-15          UK       NaN   
157      157      bp/1702         BP  2017-01-16          UK       NaN   
158      158      bp/1703         BP  2017-02-25          UK       NaN   
159      159      bp/1704         BP  2017-03-11          UK       NaN   
160      160      bp/1705         BP  2017-03-25          UK       NaN   
161      161      bp/1706         BP  2017-07-29          UK       NaN   
162      162      bp/1707         BP  2017-10-21          UK       NaN   
163      163      bp/1708         BP  2017-11-04          UK       NaN   
164      164      bp/1709         BP  2017-11-25          UK       NaN   
165      165      bp/1710         BP  2017-12-09          UK       NaN   
166      166      bp/1801         BP  2018-01-21          UK       NaN   
167      167      bp/1802         BP  2018-01-20          UK       NaN   
1239    1239     epa/1704        EPA  2017-08-12          UK       NaN   
1317    1317  gpc-gb/1601     GPC-GB  2016-10-29          UK       NaN   
1318    1318  gpc-gb/1701     GPC-GB  2017-11-11          UK       NaN   

              MeetTown                                           MeetName  
137              Dover  British Classic Mens Powerlifting Championship...  
138                NaN  British Senior & Junior Equipped Powerlifting ...  
139         Horncastle  British Equipped Masters Powerlifting Champion...  
140         Horncastle  British Classic Masters Powerlifting Champions...  
141                NaN         British Equipped Bench Press Championships  
142             London              British Women's Classic Championships  
143            Glasgow                                       Four Nations  
144          Ashington                     Home Nations Championship 2015  
145                NaN            British Mens Classic Championships 2015  
146                NaN          British Womens Classic Championships 2015  
147                NaN          British Junior Classic Championships 2015  
148                NaN                British Equipped Championships 2015  
149         Horncastle                       British Classic Masters 2015  
150         Horncastle          British Classic Bench Press Championships  
151         Horncastle         British Equipped Bench Press Championships  
152   Northamptonshire                           British Classic Men 2016  
153         Horncastle               Women's British Classic Championship  
154         Horncastle              British Ben

In [11]:
df[df['MeetCountry']=='UK']

MeetID     MeetPath Federation        Date MeetCountry MeetState  \
137      137      bp/1401         BP  2014-10-04          UK       NaN   
138      138      bp/1402         BP  2014-07-12          UK       NaN   
139      139      bp/1403         BP  2014-03-16          UK       NaN   
140      140      bp/1404         BP  2014-03-15          UK       NaN   
141      141      bp/1405         BP  2014-01-15          UK       NaN   
142      142      bp/1406         BP  2014-09-20          UK       NaN   
143      143      bp/1407         BP  2014-11-29          UK       NaN   
144      144      bp/1501         BP  2015-10-24          UK       NaN   
145      145      bp/1502         BP  2015-10-03          UK       NaN   
146      146      bp/1503         BP  2015-09-19          UK       NaN   
147      147      bp/1504         BP  2015-10-31          UK       NaN   
148      148      bp/1505         BP  2015-11-04          UK       NaN   
149      149      bp/1506         BP  2015-07-03          UK       NaN   
150      150      bp/1507         BP  2015-08-02          UK       NaN   
151      151      bp/1508         BP  2015-02-07          UK       NaN   
152      152      bp/1601         BP  2016-10-01          UK       NaN   
153      153      bp/1602         BP  2016-09-17          UK       NaN   
154      154      bp/1603         BP  2016-01-23          UK       NaN   
155      155      bp/1604         BP  2016-03-27          UK       NaN   
156      156      bp/1701         BP  2017-01-15          UK       NaN   
157      157      bp/1702         BP  2017-01-16          UK       NaN   
158      158      bp/1703         BP  2017-02-25          UK       NaN   
159      159      bp/1704         BP  2017-03-11          UK       NaN   
160      160      bp/1705         BP  2017-03-25          UK       NaN   
161      161      bp/1706         BP  2017-07-29          UK       NaN   
162      162      bp/1707         BP  2017-10-21          UK       NaN   
163      163      bp/1708         BP  2017-11-04          UK       NaN   
164      164      bp/1709         BP  2017-11-25          UK       NaN   
165      165      bp/1710         BP  2017-12-09          UK       NaN   
166      166      bp/1801         BP  2018-01-21          UK       NaN   
167      167      bp/1802         BP  2018-01-20          UK       NaN   
1239    1239     epa/1704        EPA  2017-08-12          UK       NaN   
1317    1317  gpc-gb/1601     GPC-GB  2016-10-29          UK       NaN   
1318    1318  gpc-gb/1701     GPC-GB  2017-11-11          UK       NaN   

              MeetTown                                           MeetName  
137              Dover  British Classic Mens Powerlifting Championship...  
138                NaN  British Senior & Junior Equipped Powerlifting ...  
139         Horncastle  British Equipped Masters Powerlifting Champion...  
140         Horncastle  British Classic Masters Powerlifting Champions...  
141                NaN         British Equipped Bench Press Championships  
142             London              British Women's Classic Championships  
143            Glasgow                                       Four Nations  
144          Ashington                     Home Nations Championship 2015  
145                NaN            British Mens Classic Championships 2015  
146                NaN          British Womens Classic Championships 2015  
147                NaN          British Junior Classic Championships 2015  
148                NaN                British Equipped Championships 2015  
149         Horncastle                       British Classic Masters 2015  
150         Horncastle          British Classic Bench Press Championships  
151         Horncastle         British Equipped Bench Press Championships  
152   Northamptonshire                           British Classic Men 2016  
153         Horncastle               Women's British Classic Championship  
154         Horncastle              British Ben

In [12]:
df.columns

Index(['MeetID', 'MeetPath', 'Federation', 'Date', 'MeetCountry', 'MeetState',
       'MeetTown', 'MeetName'],
      dtype='object')

In [13]:
# df[(df['MeetCountry'] == 'UK') | (df['MeetCountry'] == 'Australia')]
df[((df['MeetCountry'] == 'UK') |(df['MeetCountry']=='Australia')) & (df['MeetTown']=='Dover')]

MeetID MeetPath Federation        Date MeetCountry MeetState MeetTown  \
137     137  bp/1401         BP  2014-10-04          UK       NaN    Dover   

                                              MeetName  
137  British Classic Mens Powerlifting Championship...

In [14]:
df.groupby('MeetCountry').count()

MeetID  MeetPath  Federation  Date  MeetState  MeetTown  \
MeetCountry                                                                  
Argentina               1         1           1     1          0         1   
Australia             532       532         532   532        530       516   
Belarus                 3         3           3     3          0         3   
Brazil                  3         3           3     3          1         2   
Canada               1066      1066        1066  1066       1059      1039   
Cayman Islands          1         1           1     1          0         1   
Colombia                3         3           3     3          0         2   
Czechia                12        12          12    12          0        12   
Denmark                 2         2           2     2          0         2   
England                16        16          16    16          0        14   
Estonia                 4         4           4     4          0         4   
Finland                16        16          16    16          0        16   
France                  6         6           6     6          0         6   
Germany                 3         3           3     3          0         3   
Greece                  2         2           2     2          0         2   
Iceland                 1         1           1     1          0         1   
India                   5         5           5     5          3         5   
Indonesia               1         1           1     1          0         1   
Ireland                21        21          21    21          0         3   
Israel                  1         1           1     1          0         1   
Italy                   6         6           6     6          0         6   
Japan                   1         1           1     1          0         1   
Kazakhstan              2         2           2     2          0         2   
Luxembourg              2         2           2     2          0         2   
Malaysia                1         1           1     1          0         0   
N.Ireland              36        36          36    36          0         0   
Netherlands             1         1           1     1          0         1   
New Caledonia           1         1           1     1          0         1   
New Zealand           195       195         195   195        172       183   
Norway               2521      2521        2521  2521          0      2442   
Peru                    1         1           1     1          0         1   
Poland                  3         3           3     3          0         3   
Puerto Rico             2         2           2     2          0         2   
Russia                 43        43          43    43          0        25   
Scotland                4         4           4     4          0         4   
Serbia                  7         7           7     7          0         7   
Singapore               1         1           1     1          0         0   
South Africa            8         8           8     8          0         8   
Spain                   8         8           8     8          0         8   
Sweden                  4         4           4     4          0         4   
UK                     34        34          34    34          0        16   
US Virgin Islands       3         3           3     3          0         3   
USA                  3894      3894        3894  3894       3731      2616   
Ukraine                 4         4           4     4          0         4   
Wales                   1         1           1     1          0         0   

                   MeetName  
MeetCountry                  
Argentina                 1  
Australia               532  
Belarus                   3  
Brazil                    3  
Canada                 1066  
Cayman Islands            1  
Colombia                  3  
Czechia                  12  
Denmark                   2  
England               

In [15]:
df.groupby(['MeetCountry','MeetState']).count().sort_values('MeetID')

MeetID  MeetPath  Federation  Date  MeetTown  MeetName
MeetCountry MeetState                                                        
Brazil      SP              1         1           1     1         0         1
India       WB              1         1           1     1         1         1
New Zealand MWT             1         1           1     1         1         1
USA         DC              1         1           1     1         0         1
India       MH              2         2           2     2         2         2
...                       ...       ...         ...   ...       ...       ...
USA         PA            164       164         164   164       113       164
            OH            166       166         166   166       120       166
Canada      ON            290       290         290   290       290       290
USA         CA            399       399         399   399       365       399
            TX            872       872         872   872       767       872

[81 rows x 6 columns]

In [16]:
df['MeetState']

0       NC
1       MO
2       NC
3       SC
4       SC
        ..
8477    OH
8478    OH
8479    OH
8480    OH
8481    OH
Name: MeetState, Length: 8482, dtype: object

In [17]:
df.columns

Index(['MeetID', 'MeetPath', 'Federation', 'Date', 'MeetCountry', 'MeetState',
       'MeetTown', 'MeetName'],
      dtype='object')

In [18]:
df.groupby('MeetPath').count()

MeetID  Federation  Date  MeetCountry  MeetState  \
MeetPath                                                                      
365strong/1601                  1           1     1            1          1   
365strong/1602                  1           1     1            1          1   
365strong/1603                  1           1     1            1          1   
365strong/1604                  1           1     1            1          1   
365strong/1605                  1           1     1            1          1   
...                           ...         ...   ...          ...        ...   
xpc/2015-finals                 1           1     1            1          1   
xpc/2016-bench-freak-show       1           1     1            1          1   
xpc/2016-elite-finals           1           1     1            1          1   
xpc/2016-pro-finals             1           1     1            1          1   
xpc/2017-finals                 1           1     1            1          1   

                           MeetTown  MeetName  
MeetPath                                       
365strong/1601                    1         1  
365strong/1602                    1         1  
365strong/1603                    1         1  
365strong/1604                    1         1  
365strong/1605                    1         1  
...                             ...       ...  
xpc/2015-finals                   1         1  
xpc/2016-bench-freak-show         1         1  
xpc/2016-elite-finals             1         1  
xpc/2016-pro-finals               1         1  
xpc/2017-finals                   1         1  

[8482 rows x 7 columns]

In [19]:
df.MeetState.value_counts()

MeetState
TX     872
CA     399
ON     290
OH     166
PA     164
      ... 
DE       2
WB       1
MWT      1
DC       1
SP       1
Name: count, Length: 80, dtype: int64

In [20]:
df['Date'].dtypes

dtype('O')

In [21]:
df['Date']=pd.to_datetime(df['Date'])

In [22]:
df['Date'].dtypes

dtype('<M8[ns]')

In [23]:
df['year']=df.Date.dt.year
df['month']=df.Date.dt.month
df['day']=df.Date.dt.day

In [24]:
df

MeetID                   MeetPath Federation       Date MeetCountry  \
0          0             365strong/1601  365Strong 2016-10-29         USA   
1          1             365strong/1602  365Strong 2016-11-19         USA   
2          2             365strong/1603  365Strong 2016-07-09         USA   
3          3             365strong/1604  365Strong 2016-06-11         USA   
4          4             365strong/1605  365Strong 2016-04-10         USA   
...      ...                        ...        ...        ...         ...   
8477    8477            xpc/2015-finals        XPC 2015-03-06         USA   
8478    8478  xpc/2016-bench-freak-show        XPC 2016-03-04         USA   
8479    8479      xpc/2016-elite-finals        XPC 2016-03-04         USA   
8480    8480        xpc/2016-pro-finals        XPC 2016-03-05         USA   
8481    8481            xpc/2017-finals        XPC 2017-03-03         USA   

     MeetState   MeetTown                                           MeetName  \
0           NC  Charlotte  2016 Junior & Senior National Powerlifting Cha...   
1           MO      Ozark                  Thanksgiving Powerlifting Classic   
2           NC  Charlotte                             Charlotte Europa Games   
3           SC  Rock Hill                   Carolina Cup Push Pull Challenge   
4           SC  Rock Hill                              Eastern USA Challenge   
...        ...        ...                                                ...   
8477        OH   Columbus                                           2015 XPC   
8478        OH   Columbus                          2016 XPC Bench Freak Show   
8479        OH   Columbus                              2016 XPC Elite Finals   
8480        OH   Columbus                                2016 XPC PRO Finals   
8481        OH   Columbus                                    2017 XPC Finals   

      year  month  day  
0     2016     10   29  
1     2016     11   19  
2     2016      7    9  
3     2016      6   11  
4     2016      4   10  
...    ...    ...  ...  
8477  2015      3    6  
8478  2016      3    4  
8479  2016      3    4  
8480  2016      3    5  
8481  2017      3    3  

[8482 rows x 11 columns]

In [25]:
df.year.value_counts()

year
2017    1640
2016    1475
2015     865
2014     631
2013     468
2012     385
2011     324
2010     264
2008     234
2007     221
2009     217
2001     200
2000     189
2004     187
2005     172
2006     168
2003     161
2002     138
1991     109
1998      90
1999      74
2018      46
1997      39
1996      28
1982      20
1995      19
1974      18
1990      17
1975      12
1987       9
1983       8
1986       7
1989       7
1985       6
1979       6
1984       5
1980       4
1993       4
1988       3
1994       3
1992       3
1978       2
1981       2
1977       1
1976       1
Name: count, dtype: int64

In [26]:
df.month.value_counts()

month
2     1085
1      800
12     782
10     781
4      753
6      702
3      656
5      652
9      650
11     639
8      552
7      430
Name: count, dtype: int64

In [27]:
df.groupby('year').count()

MeetID  MeetPath  Federation  Date  MeetCountry  MeetState  MeetTown  \
year                                                                         
1974      18        18          18    18           18          1        18   
1975      12        12          12    12           12          0        12   
1976       1         1           1     1            1          1         1   
1977       1         1           1     1            1          1         1   
1978       2         2           2     2            2          0         2   
1979       6         6           6     6            6          3         5   
1980       4         4           4     4            4          1         4   
1981       2         2           2     2            2          1         2   
1982      20        20          20    20           20          1        20   
1983       8         8           8     8            8          2         8   
1984       5         5           5     5            5          4         5   
1985       6         6           6     6            6          2         6   
1986       7         7           7     7            7          5         5   
1987       9         9           9     9            9          2         9   
1988       3         3           3     3            3          2         3   
1989       7         7           7     7            7          1         7   
1990      17        17          17    17           17          0        17   
1991     109       109         109   109          109          1       103   
1992       3         3           3     3            3          1         3   
1993       4         4           4     4            4          4         3   
1994       3         3           3     3            3          1         3   
1995      19        19          19    19           19         15        19   
1996      28        28          28    28           28         24        25   
1997      39        39          39    39           39         20        37   
1998      90        90          90    90           90         32        86   
1999      74        74          74    74           74         61        71   
2000     189       189         189   189          189         74       181   
2001     200       200         200   200          200         99       191   
2002     138       138         138   138          138         21       135   
2003     161       161         161   161          161         41       154   
2004     187       187         187   187          187         60       181   
2005     172       172         172   172          172         53       164   
2006     168       168         168   168          168         45       156   
2007     221       221         221   221          221         89       203   
2008     234       234         234   234          234        117       214   
2009     217       217         217   217          217        103       206   
2010     264       264         264   264          264        114       232   
2011     324       324         324   324          324        159       282   
2012     385       385         385   385          385        212       340   
2013     468       468         468   468          468        276       394   
2014     631       631         631   631          631        461       453   
2015     865       865         865   865          865        648       616   
2016    1475      1475        1475  1475         1475       1252      1152   
2017    1640      1640        1640  1640         1640       1443      1221   
2018      46        46          46    46           46         43        23   

      MeetName  month   day  
year                         
1974        18     18    18  
1975        12     12    12  
1976         1      1     1  
1977         1      1     1  
1978         2      2     2  
1979         6      6     6  
1980         4      4     4  
1981         2      2     2  
1982        20     20    20  
1983     

In [28]:
df.groupby('year').size()

year
1974      18
1975      12
1976       1
1977       1
1978       2
1979       6
1980       4
1981       2
1982      20
1983       8
1984       5
1985       6
1986       7
1987       9
1988       3
1989       7
1990      17
1991     109
1992       3
1993       4
1994       3
1995      19
1996      28
1997      39
1998      90
1999      74
2000     189
2001     200
2002     138
2003     161
2004     187
2005     172
2006     168
2007     221
2008     234
2009     217
2010     264
2011     324
2012     385
2013     468
2014     631
2015     865
2016    1475
2017    1640
2018      46
dtype: int64

In [29]:
df=pd.read_csv('titanic.csv')

In [30]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [32]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [35]:
df.drop(columns='Cabin',inplace=True)

In [36]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [37]:
df.duplicated().sum()

np.int64(0)

In [47]:
df.groupby('Sex').Survived.value_counts()

Sex     Survived
female  1           233
        0            81
male    0           468
        1           109
Name: count, dtype: int64

In [49]:
df.groupby(['Sex','Age']).Survived.value_counts()

Sex     Age    Survived
female  0.75   1           2
        1.00   1           2
        2.00   0           4
               1           2
        3.00   0           1
                          ..
male    70.00  0           2
        70.50  0           1
        71.00  0           2
        74.00  0           1
        80.00  1           1
Name: count, Length: 216, dtype: int64

In [53]:
df.groupby('Survived').Pclass.value_counts()

Survived  Pclass
0         3         372
          2          97
          1          80
1         1         136
          3         119
          2          87
Name: count, dtype: int64

In [56]:
df.Fare.mean()

np.float64(32.204207968574636)

In [58]:
df.Fare.max()

np.float64(512.3292)

In [60]:
df.Fare.min()

np.float64(0.0)

In [62]:
df[df['Fare']==0].count().sum()

np.int64(157)

In [64]:
df[df['Fare']==0].groupby('Pclass').size()

Pclass
1    5
2    6
3    4
dtype: int64

In [66]:
df[df['Fare']==0].groupby('Pclass').size()

Pclass
1    5
2    6
3    4
dtype: int64

In [68]:
df.shape

(891, 11)

In [2]:
!pip install matplotlib

   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 18.1 MB/s eta 0:00:01
   --- ------------------------------------ 0.8/8.1 MB 3.1 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/8.1 MB 2.4 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/8.1 MB 2.2 MB/s eta 0:00:03
   --------- ------------------------------ 1.8/8.1 MB 2.1 MB/s eta 0:00:04
   ----------- ---------------------------- 2.4/8.1 MB 2.0 MB/s eta 0:00:03
   ------------ --------------------------- 2.6/8.1 MB 2.0 MB/s eta 0:00:03
   --------------- ------------------------ 3.1/8.1 MB 2.0 MB/s eta 0:00:03
   ------------------ --------------------- 3.7/8.1 MB 2.0 MB/s eta 0:00:03
   ------------------- -------------------- 3.9/8.1 MB 2.0 MB/s eta 0:00:03
   ---------------------- ----------------- 4.5/8.1 MB 2.0 MB/s eta 0:00:02
   ----------------------

In [3]:
import pandas as pd 
import matplotlib.pyplot as plt

In [5]:
pd.Series(['Ahmed','Adel','Said'],name='names',index=[10,20,30])

10    Ahmed
20     Adel
30     Said
Name: names, dtype: object

In [8]:
pd.DataFrame(
        {'ahmed':[12,13,14],
        'Ali':[1,2,3]
    })

ahmed  Ali
0     12    1
1     13    2
2     14    3

In [51]:
import pandas as pd
df=pd.read_csv('titanic.csv')

In [11]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [12]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [14]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [17]:
df.describe(include='O')

Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

In [18]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [19]:
df.iloc[20:31,:]

PassengerId  Survived  Pclass  \
20           21         0       2   
21           22         1       2   
22           23         1       3   
23           24         1       1   
24           25         0       3   
25           26         1       3   
26           27         0       3   
27           28         0       1   
28           29         1       3   
29           30         0       3   
30           31         0       1   

                                                 Name     Sex   Age  SibSp  \
20                               Fynney, Mr. Joseph J    male  35.0      0   
21                              Beesley, Mr. Lawrence    male  34.0      0   
22                        McGowan, Miss. Anna "Annie"  female  15.0      0   
23                       Sloper, Mr. William Thompson    male  28.0      0   
24                      Palsson, Miss. Torborg Danira  female   8.0      3   
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
26                            Emir, Mr. Farred Chehab    male   NaN      0   
27                     Fortune, Mr. Charles Alexander    male  19.0      3   
28                      O'Dwyer, Miss. Ellen "Nellie"  female   NaN      0   
29                                Todoroff, Mr. Lalio    male   NaN      0   
30                           Uruchurtu, Don. Manuel E    male  40.0      0   

    Parch    Ticket      Fare        Cabin Embarked  
20      0    239865   26.0000          NaN        S  
21      0    248698   13.0000          D56        S  
22      0    330923    8.0292          NaN        Q  
23      0    113788   35.5000           A6        S  
24      1    349909   21.0750          NaN        S  
25      5    347077   31.3875          NaN        S  
26      0      2631    7.2250          NaN        C  
27      2     19950  263.0000  C23 C25 C27        S  
28      0    330959    7.8792          NaN        Q  
29      0    349216    7.8958          NaN        S  
30      0  PC 17601   27.7208          NaN        C

In [20]:
df.iloc[:,0:2]

PassengerId  Survived
0              1         0
1              2         1
2              3         1
3              4         1
4              5         0
..           ...       ...
886          887         0
887          888         1
888          889         0
889          890         1
890          891         0

[891 rows x 2 columns]

In [21]:
df.loc[:,['Pclass','Age']]

Pclass   Age
0         3  22.0
1         1  38.0
2         3  26.0
3         1  35.0
4         3  35.0
..      ...   ...
886       2  27.0
887       1  19.0
888       3   NaN
889       1  26.0
890       3  32.0

[891 rows x 2 columns]

In [23]:
# df=df.drop('Age',axis=1)

In [26]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [27]:
df.set_index('PassengerId')

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
...               ...     ...   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
...                                                        ...     ...   ...   
887                                      Montvila, Rev. Juozas    male  27.0   
888                               Graham, Miss. Margaret Edith  female  19.0   
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
890                                      Behr, Mr. Karl Howell    male  26.0   
891                                        Dooley, Mr. Patrick    male  32.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
...            ...    ...               ...      ...   ...      ...  
887              0      0            211536  13.0000   NaN        S  
888              0      0            112053  30.0000   B42        S  
889              1      2        W./C. 6607  23.4500   NaN        S  
890              0      0            111369  30.0000  C148        C  
891              0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [32]:
# df.Embarked.nunique()  number of ubique values 

3

In [34]:
df.Embarked.value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [46]:
data=pd.read_csv('titanic.csv')

In [47]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [48]:
fare_mean=data['Fare'].mean()
data['fare_mean']=data['Fare']-fare_mean

In [49]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  fare_mean  
0      0         A/5 21171   7.2500   NaN        S -24.954208  
1      0          PC 17599  71.2833   C85        C  39.079092  
2      0  STON/O2. 3101282   7.9250   NaN        S -24.279208  
3      0            113803  53.1000  C123        S  20.895792  
4      0            373450   8.0500   NaN        S -24.154208

In [54]:
df[(df['Fare']>20) & (df['Sex'].str.lower()=='male')]

PassengerId  Survived  Pclass                                     Name  \
6              7         0       1                  McCarthy, Mr. Timothy J   
7              8         0       3           Palsson, Master. Gosta Leonard   
13            14         0       3              Andersson, Mr. Anders Johan   
16            17         0       3                     Rice, Master. Eugene   
20            21         0       2                     Fynney, Mr. Joseph J   
..           ...       ...     ...                                      ...   
848          849         0       2                        Harper, Rev. John   
850          851         0       3  Andersson, Master. Sigvard Harald Elias   
857          858         1       1                   Daly, Mr. Peter Denis    
867          868         0       1     Roebling, Mr. Washington Augustus II   
889          890         1       1                    Behr, Mr. Karl Howell   

      Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  Fare_mean  
6    male  54.0      0      0     17463  51.8625   E46        S  32.204208  
7    male   2.0      3      1    349909  21.0750   NaN        S  32.204208  
13   male  39.0      1      5    347082  31.2750   NaN        S  32.204208  
16   male   2.0      4      1    382652  29.1250   NaN        Q  32.204208  
20   male  35.0      0      0    239865  26.0000   NaN        S  32.204208  
..    ...   ...    ...    ...       ...      ...   ...      ...        ...  
848  male  28.0      0      1    248727  33.0000   NaN        S  32.204208  
850  male   4.0      4      2    347082  31.2750   NaN        S  32.204208  
857  male  51.0      0      0    113055  26.5500   E17        S  32.204208  
867  male  31.0      0      0  PC 17590  50.4958   A24        S  32.204208  
889  male  26.0      0      0    111369  30.0000  C148        C  32.204208  

[204 rows x 13 columns]

In [5]:
df.Sex.str.contains('Male')

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Sex, Length: 891, dtype: bool

In [57]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Fare_mean        0
dtype: int64

In [18]:
df.groupby('Sex').Fare.count()

Sex
female    314
male      577
Name: Fare, dtype: int64

In [20]:
df.sort_values(by='Sex',ascending=False)

PassengerId  Survived  Pclass                                     Name  \
0              1         0       3                  Braund, Mr. Owen Harris   
495          496         0       3                    Yousseff, Mr. Gerious   
536          537         0       1        Butt, Major. Archibald Willingham   
538          539         0       3                 Risien, Mr. Samuel Beard   
543          544         1       2                        Beane, Mr. Edward   
..           ...       ...     ...                                      ...   
257          258         1       1                     Cherry, Miss. Gladys   
678          679         0       3  Goodwin, Mrs. Frederick (Augusta Tyler)   
677          678         1       3                  Turja, Miss. Anna Sofia   
448          449         1       3           Baclini, Miss. Marie Catherine   
520          521         1       1                    Perreault, Miss. Anne   

        Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked  
0      male  22.0      1      0  A/5 21171   7.2500   NaN        S  
495    male   NaN      0      0       2627  14.4583   NaN        C  
536    male  45.0      0      0     113050  26.5500   B38        S  
538    male   NaN      0      0     364498  14.5000   NaN        S  
543    male  32.0      1      0       2908  26.0000   NaN        S  
..      ...   ...    ...    ...        ...      ...   ...      ...  
257  female  30.0      0      0     110152  86.5000   B77        S  
678  female  43.0      1      6    CA 2144  46.9000   NaN        S  
677  female  18.0      0      0       4138   9.8417   NaN        S  
448  female   5.0      2      1       2666  19.2583   NaN        C  
520  female  30.0      0      0      12749  93.5000   B73        S  

[891 rows x 12 columns]

In [23]:
df1=pd.DataFrame({
    'ahmed':[1,2,3,4,5]
})
df2=pd.DataFrame({
    'Ali':[5,6,7,8]
})

In [31]:
x=pd.concat([df1,df2],axis=1)
x

ahmed  Ali
0      1  5.0
1      2  6.0
2      3  7.0
3      4  8.0
4      5  NaN

In [32]:
x.reset_index()

index  ahmed  Ali
0      0      1  5.0
1      1      2  6.0
2      2      3  7.0
3      3      4  8.0
4      4      5  NaN

In [ ]:
pd.merge(df1,df2,)

In [38]:
x=[]
for i in df.Age:
    x=i-10
    

In [40]:
# df.Age.apply(lambda x :x-10)

0      12.0
1      28.0
2      16.0
3      25.0
4      25.0
       ... 
886    17.0
887     9.0
888     NaN
889    16.0
890    22.0
Name: Age, Length: 891, dtype: float64

In [43]:
test=lambda x: x*10

In [44]:
test(20)

200

In [56]:
%%timeit
df['Age']=df['Age'].apply(lambda x: x-10)

250 μs ± 1.05 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [57]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex      Age  \
0                              Braund, Mr. Owen Harris    male -81098.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female -81082.0   
2                               Heikkinen, Miss. Laina  female -81094.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female -81085.0   
4                             Allen, Mr. William Henry    male -81085.0   
..                                                 ...     ...      ...   
886                              Montvila, Rev. Juozas    male -81093.0   
887                       Graham, Miss. Margaret Edith  female -81101.0   
888           Johnston, Miss. Catherine Helen "Carrie"  female      NaN   
889                              Behr, Mr. Karl Howell    male -81094.0   
890                                Dooley, Mr. Patrick    male -81088.0   

     SibSp  Parch            Ticket     Fare Cabin Embarked  
0        1      0         A/5 21171   7.2500   NaN        S  
1        1      0          PC 17599  71.2833   C85        C  
2        0      0  STON/O2. 3101282   7.9250   NaN        S  
3        1      0            113803  53.1000  C123        S  
4        0      0            373450   8.0500   NaN        S  
..     ...    ...               ...      ...   ...      ...  
886      0      0            211536  13.0000   NaN        S  
887      0      0            112053  30.0000   B42        S  
888      1      2        W./C. 6607  23.4500   NaN        S  
889      0      0            111369  30.0000  C148        C  
890      0      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [55]:
df.Age.dtype

dtype('float64')

In [58]:
import numpy as np

In [66]:
x=np.array(
    [
        [[1,2],
         [3,4]],
        [[5,6],[7,8]]

        
    ]
)

In [68]:
x.shape

(2, 2, 2)

In [71]:
y=np.array([1,2,3,4,5])

In [72]:
y.shape

(5,)

In [74]:
x.ndim

3

In [3]:
import pandas as pd
import numpy as np

In [8]:
x=np.array([[1,2,3,4,5],[6,7,8,9,1]])
print(x)

[[1 2 3 4 5]
 [6 7 8 9 1]]


In [9]:
x.shape

(2, 5)

In [12]:
y=np.array(
    [
        [[1,2],
        [3,4]],
        [[5,6],[
            7,8
        ]]
        
    ]
)

In [13]:
y

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
y.shape

(2, 2, 2)

In [15]:
y.ndim

3

In [16]:
# y.size   في كام elemeny

8

In [17]:
x.dtype

dtype('int64')

In [23]:
zeros=np.zeros((3,3),np.int32)

In [28]:
ones=np.ones((3,3),np.int64)
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [29]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [30]:
np.full((4,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [31]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [32]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
# np.random.seed(33) كل مره بتطلع نفس الرقم كل مره 
# np.random.randint(low=0,high=10)  بتطلع كل مره رقم عشوائي بين 0و10

9

In [48]:
# np.random.random() الرقم بيبقي بين 0 و1 

0.8703956883469495

In [49]:
np.random.randn()

0.11601839050684011

In [51]:
np.random.randint(low=1,high=10,size=(3,3))

array([[8, 7, 1],
       [1, 7, 7],
       [1, 5, 9]], dtype=int32)

In [57]:
# np.random.rand(2, 3)  مصفوفه بين 0 و1 
#  الفرق بين random.random() , random.rand() 
#  ان random.random بتطلع رقم واحد بس 
#random.rand() بتطلع مصفوفه او مجمووعه من الارقام
np.random.rand(2,2)

array([[0.42174821, 0.56086662],
       [0.11992205, 0.12022708]])

In [58]:
np.random.random()

0.91402350067747

In [60]:
np.random.randint(low=1,high=10,size=(2,2))

array([[3, 6],
       [8, 2]], dtype=int32)

In [64]:
x=np.random.randn(5,5)
x

array([[ 0.64069478, -0.61430226, -1.66142163,  0.47041278,  0.0683247 ],
       [ 0.43291045,  0.05558087, -0.51597797, -0.64280571,  1.92218927],
       [ 0.83116227, -1.44748557, -1.20591635, -0.33512452,  1.05581423],
       [-0.65690865,  1.93684627,  1.31496727,  0.50366399, -0.09175566],
       [ 0.33882096,  1.02965437,  0.57802364,  0.94577621,  0.61004495]])

In [66]:
x[0:5,-2:]

array([[ 0.47041278,  0.0683247 ],
       [-0.64280571,  1.92218927],
       [-0.33512452,  1.05581423],
       [ 0.50366399, -0.09175566],
       [ 0.94577621,  0.61004495]])

In [67]:
x*5

array([[ 3.20347388, -3.0715113 , -8.30710817,  2.35206388,  0.34162349],
       [ 2.16455226,  0.27790437, -2.57988983, -3.21402857,  9.61094637],
       [ 4.15581137, -7.23742787, -6.02958174, -1.6756226 ,  5.27907114],
       [-3.28454325,  9.68423134,  6.57483636,  2.51831997, -0.4587783 ],
       [ 1.69410481,  5.14827185,  2.89011821,  4.72888105,  3.05022473]])

In [68]:
x.mean()

np.float64(0.22252754770184996)

In [70]:
x.max()

np.float64(1.9368462674306062)

In [72]:
x.std()

np.float64(0.9277528420446743)

In [74]:
y=x**2

In [75]:
# np.dot(x,y) بضرب الاتنين matriceses في بعض 

array([[-0.78904933, -1.40402412,  0.02511697, -0.11819365, -4.08941164],
       [-0.22505426, -1.29106864, -0.00985834,  1.61713412,  0.34213881],
       [-0.78658466, -2.35528712, -0.07149562,  0.30979647, -6.29848913],
       [ 1.20856477,  4.30537951,  1.45489244,  0.84831253,  8.58915999],
       [ 1.20953085,  5.53684647,  3.8891663 ,  1.35094914,  4.68530259]])

In [76]:
# x@y هي هي لو عملت x.dot(y)

array([[-0.78904933, -1.40402412,  0.02511697, -0.11819365, -4.08941164],
       [-0.22505426, -1.29106864, -0.00985834,  1.61713412,  0.34213881],
       [-0.78658466, -2.35528712, -0.07149562,  0.30979647, -6.29848913],
       [ 1.20856477,  4.30537951,  1.45489244,  0.84831253,  8.58915999],
       [ 1.20953085,  5.53684647,  3.8891663 ,  1.35094914,  4.68530259]])

In [78]:
x

array([[ 0.64069478, -0.61430226, -1.66142163,  0.47041278,  0.0683247 ],
       [ 0.43291045,  0.05558087, -0.51597797, -0.64280571,  1.92218927],
       [ 0.83116227, -1.44748557, -1.20591635, -0.33512452,  1.05581423],
       [-0.65690865,  1.93684627,  1.31496727,  0.50366399, -0.09175566],
       [ 0.33882096,  1.02965437,  0.57802364,  0.94577621,  0.61004495]])

In [79]:
# x.T بتخلي الصف عمود والعكس 

array([[ 0.64069478,  0.43291045,  0.83116227, -0.65690865,  0.33882096],
       [-0.61430226,  0.05558087, -1.44748557,  1.93684627,  1.02965437],
       [-1.66142163, -0.51597797, -1.20591635,  1.31496727,  0.57802364],
       [ 0.47041278, -0.64280571, -0.33512452,  0.50366399,  0.94577621],
       [ 0.0683247 ,  1.92218927,  1.05581423, -0.09175566,  0.61004495]])

In [81]:
x.reshape(25,1)

array([[ 0.64069478],
       [-0.61430226],
       [-1.66142163],
       [ 0.47041278],
       [ 0.0683247 ],
       [ 0.43291045],
       [ 0.05558087],
       [-0.51597797],
       [-0.64280571],
       [ 1.92218927],
       [ 0.83116227],
       [-1.44748557],
       [-1.20591635],
       [-0.33512452],
       [ 1.05581423],
       [-0.65690865],
       [ 1.93684627],
       [ 1.31496727],
       [ 0.50366399],
       [-0.09175566],
       [ 0.33882096],
       [ 1.02965437],
       [ 0.57802364],
       [ 0.94577621],
       [ 0.61004495]])

In [85]:
a=[1,2,3]
b=[4,5,6]
# print(np.hstack([a,b])) horizantel يعني جنب بعض 
# print(np.vstack([a,b])) vertical واحده فووق وواحده تحت 

In [87]:
a=[2,3,4]
b=[6,7,8]
print(np.hstack([a,b]))
print(np.vstack([a,b]))

[2 3 4 6 7 8]
[[2 3 4]
 [6 7 8]]


In [89]:
# broad casting 
z=x+10

In [90]:
# masking 
z[z>9]

array([10.64069478,  9.38569774, 10.47041278, 10.0683247 , 10.43291045,
       10.05558087,  9.48402203,  9.35719429, 11.92218927, 10.83116227,
        9.66487548, 11.05581423,  9.34309135, 11.93684627, 11.31496727,
       10.50366399,  9.90824434, 10.33882096, 11.02965437, 10.57802364,
       10.94577621, 10.61004495])

In [95]:
import timeit
arr = np.arange(1000)
%%timeit arr * 2


UsageError: Line magic function `%%timeit` not found.


In [2]:
import numpy as np

In [3]:
num1=np.array(1)
num2=np.array(2)

In [4]:
num1/num2

np.float64(0.5)

In [5]:
num1=np.array(10)
nump2=np.array(2.5)

In [6]:
num1/num2

np.float64(5.0)

In [18]:
# quiz
import pandas as pd
fruits=pd.DataFrame([
    {
        'Apples':30,
        'Bananas':21
    }
])
fruits

Apples  Bananas
0      30       21

In [24]:
fruits_sales=pd.DataFrame({
    'Apples':[35,41],
    'Bananas':[21,34]
},
    index=['2017 Sales','2018 Sales']
                         
)

In [25]:
fruits_sales

Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [29]:
ingredients=pd.Series(
    {
        'Flour': '4 cups',
        'Milk' : '1 cup',
        'Eggs' :  '2 large',
        'spam' : '1 can',
       
    },
    name='Dinner'
)

In [30]:
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
spam       1 can
Name: Dinner, dtype: object

In [33]:
reviews=pd.read_csv('winemag-data-130k-v2(2).csv')

In [34]:
reviews

Unnamed: 0   country  \
0                0     Italy   
1                1  Portugal   
2                2        US   
3                3        US   
4                4        US   
...            ...       ...   
129966      129966   Germany   
129967      129967        US   
129968      129968    France   
129969      129969    France   
129970      129970    France   

                                              description  \
0       Aromas include tropical fruit, broom, brimston...   
1       This is ripe and fruity, a wine that is smooth...   
2       Tart and snappy, the flavors of lime flesh and...   
3       Pineapple rind, lemon pith and orange blossom ...   
4       Much like the regular bottling from 2012, this...   
...                                                   ...   
129966  Notes of honeysuckle and cantaloupe sweeten th...   
129967  Citation is given as much as a decade of bottl...   
129968  Well-drained gravel soil gives this wine its c...   
129969  A dry style of Pinot Gris, this is crisp with ...   
129970  Big, rich and off-dry, this is powered by inte...   

                                   designation  points  price  \
0                                 Vulkà Bianco      87    NaN   
1                                     Avidagos      87   15.0   
2                                          NaN      87   14.0   
3                         Reserve Late Harvest      87   13.0   
4           Vintner's Reserve Wild Child Block      87   65.0   
...                                        ...     ...    ...   
129966  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0   
129967                                     NaN      90   75.0   
129968                                   Kritt      90   30.0   
129969                                     NaN      90   32.0   
129970           Lieu-dit Harth Cuvée Caroline      90   21.0   

                 province             region_1           region_2  \
0       Sicily & Sardinia                 Etna                NaN   
1                   Douro                  NaN                NaN   
2                  Oregon    Willamette Valley  Willamette Valley   
3                Michigan  Lake Michigan Shore                NaN   
4                  Oregon    Willamette Valley  Willamette Valley   
...                   ...                  ...                ...   
129966              Mosel                  NaN                NaN   
129967             Oregon               Oregon       Oregon Other   
129968             Alsace               Alsace                NaN   
129969             Alsace               Alsace                NaN   
129970             Alsace               Alsace                NaN   

               taster_name taster_twitter_handle  \
0            Kerin O’Keefe          @kerinokeefe   
1               Roger Voss            @vossroger   
2             Paul Gregutt           @paulgwine    
3       Alexander Peartree                   NaN   
4             Paul Gregutt           @paulgwine    
...                    ...                   ...   
129966  Anna Lee C. Iijima                   NaN   
129967        Paul Gregutt           @paulgwine    
129968          Roger Voss            @vossroger   
129969          Roger Voss            @vossroger   
129970          Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
2           Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris   
3       St. Julian 2013 Reserve Late Harvest Riesling ...        Riesling   
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...      Pinot Noir   
...                                                   ...             ...   
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...        Riesling   
129967                  Citation 2004 P

In [35]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

Cows  Goats
Year 1    12     22
Year 2    20     19

In [52]:
animals=pd.DataFrame(
    {
        'cows':[12,20],
        'Goats':[22,19]
    },
    index=['Year1','Year2']
);
animals


cows  Goats
Year1    12     22
Year2    20     19

In [53]:
reviews.head()

Unnamed: 0   country                                        description  \
0           0     Italy  Aromas include tropical fruit, broom, brimston...   
1           1  Portugal  This is ripe and fruity, a wine that is smooth...   
2           2        US  Tart and snappy, the flavors of lime flesh and...   
3           3        US  Pineapple rind, lemon pith and orange blossom ...   
4           4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

In [54]:
desc=reviews['description']

In [49]:

reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   Unnamed: 0             129971 non-null  int64  
 1   country                129908 non-null  object 
 2   description            129971 non-null  object 
 3   designation            92506 non-null   object 
 4   points                 129971 non-null  int64  
 5   price                  120975 non-null  float64
 6   province               129908 non-null  object 
 7   region_1               108724 non-null  object 
 8   region_2               50511 non-null   object 
 9   taster_name            103727 non-null  object 
 10  taster_twitter_handle  98758 non-null   object 
 11  title                  129971 non-null  object 
 12  variety                129970 non-null  object 
 13  winery                 129971 non-null  object 
dtypes: float64(1), int64(2), object(11)


In [56]:
first_description=reviews['description'][0]
first_description

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

In [57]:
reviews.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='object')

In [63]:
first_row = reviews.iloc[0]
first_row

Unnamed: 0                                                               0
country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                   

In [67]:
first_descriptions=reviews.loc[1:10,'description']
first_descriptions

1     This is ripe and fruity, a wine that is smooth...
2     Tart and snappy, the flavors of lime flesh and...
3     Pineapple rind, lemon pith and orange blossom ...
4     Much like the regular bottling from 2012, this...
5     Blackberry and raspberry aromas show a typical...
6     Here's a bright, informal red that opens with ...
7     This dry and restrained wine offers spice in p...
8     Savory dried thyme notes accent sunnier flavor...
9     This has great depth of flavor with its fresh ...
10    Soft, supple plum envelopes an oaky structure ...
Name: description, dtype: object

In [69]:
sample_reviews = reviews.loc[[1, 2, 3, 5, 8]]
sample_reviews

Unnamed: 0   country                                        description  \
1           1  Portugal  This is ripe and fruity, a wine that is smooth...   
2           2        US  Tart and snappy, the flavors of lime flesh and...   
3           3        US  Pineapple rind, lemon pith and orange blossom ...   
5           5     Spain  Blackberry and raspberry aromas show a typical...   
8           8   Germany  Savory dried thyme notes accent sunnier flavor...   

            designation  points  price        province             region_1  \
1              Avidagos      87   15.0           Douro                  NaN   
2                   NaN      87   14.0          Oregon    Willamette Valley   
3  Reserve Late Harvest      87   13.0        Michigan  Lake Michigan Shore   
5          Ars In Vitro      87   15.0  Northern Spain              Navarra   
8                 Shine      87   12.0     Rheinhessen                  NaN   

            region_2         taster_name taster_twitter_handle  \
1                NaN          Roger Voss            @vossroger   
2  Willamette Valley        Paul Gregutt           @paulgwine    
3                NaN  Alexander Peartree                   NaN   
5                NaN   Michael Schachner           @wineschach   
8                NaN  Anna Lee C. Iijima                   NaN   

                                               title             variety  \
1      Quinta dos Avidagos 2011 Avidagos Red (Douro)      Portuguese Red   
2      Rainstorm 2013 Pinot Gris (Willamette Valley)          Pinot Gris   
3  St. Julian 2013 Reserve Late Harvest Riesling ...            Riesling   
5  Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...  Tempranillo-Merlot   
8  Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...      Gewürztraminer   

                winery  
1  Quinta dos Avidagos  
2            Rainstorm  
3           St. Julian  
5               Tandem  
8          Heinz Eifel

In [71]:
df=pd.DataFrame(
    {
        'country':['italy','porugal','US','US'],
        'province':['Sicily  & Sadina','Douro','California','New York'],
        'region_1':['Enta','Nan','Napa Vally','Napa'],
        'refion_2':['NaN','NaN','Napa','Finger Lakes']
        
    },
    index=[0,1,10,100]
)
df

country          province    region_1      refion_2
0      italy  Sicily  & Sadina        Enta           NaN
1    porugal             Douro         Nan           NaN
10        US        California  Napa Vally          Napa
100       US          New York        Napa  Finger Lakes

In [75]:
df.loc[1:99, 'country']


1     porugal
10         US
Name: country, dtype: object

In [79]:
df=reviews.loc[0:100,['country','variety']]
df

country                   variety
0       Italy               White Blend
1    Portugal            Portuguese Red
2          US                Pinot Gris
3          US                  Riesling
4          US                Pinot Noir
..        ...                       ...
96     France                     Gamay
97         US                  Riesling
98      Italy                Sangiovese
99         US  Bordeaux-style Red Blend
100        US                Pinot Gris

[101 rows x 2 columns]

In [86]:
italian_wines=reviews[reviews.country=='Italy']

In [87]:
italian_wines

Unnamed: 0 country                                        description  \
0                0   Italy  Aromas include tropical fruit, broom, brimston...   
6                6   Italy  Here's a bright, informal red that opens with ...   
13              13   Italy  This is dominated by oak and oak-driven aromas...   
22              22   Italy  Delicate aromas recall white flower and citrus...   
24              24   Italy  Aromas of prune, blackcurrant, toast and oak c...   
...            ...     ...                                                ...   
129929      129929   Italy  This luminous sparkler has a sweet, fruit-forw...   
129943      129943   Italy  A blend of Nero d'Avola and Syrah, this convey...   
129947      129947   Italy  A blend of 65% Cabernet Sauvignon, 30% Merlot ...   
129961      129961   Italy  Intense aromas of wild cherry, baking spice, t...   
129962      129962   Italy  Blackberry, cassis, grilled herb and toasted a...   

                      designation  points  price           province  \
0                    Vulkà Bianco      87    NaN  Sicily & Sardinia   
6                         Belsito      87   16.0  Sicily & Sardinia   
13                          Rosso      87    NaN  Sicily & Sardinia   
22                      Ficiligno      87   19.0  Sicily & Sardinia   
24                          Aynat      87   35.0  Sicily & Sardinia   
...                           ...     ...    ...                ...   
129929                        NaN      91   38.0             Veneto   
129943                    Adènzia      90   29.0  Sicily & Sardinia   
129947                   Symposio      90   20.0  Sicily & Sardinia   
129961                        NaN      90   30.0  Sicily & Sardinia   
129962  Sàgana Tenuta San Giacomo      90   40.0  Sicily & Sardinia   

                              region_1 region_2    taster_name  \
0                                 Etna      NaN  Kerin O’Keefe   
6                             Vittoria      NaN  Kerin O’Keefe   
13                                Etna      NaN  Kerin O’Keefe   
22                             Sicilia      NaN  Kerin O’Keefe   
24                             Sicilia      NaN  Kerin O’Keefe   
...                                ...      ...            ...   
129929  Prosecco Superiore di Cartizze      NaN            NaN   
129943                         Sicilia      NaN  Kerin O’Keefe   
129947                 Terre Siciliane      NaN  Kerin O’Keefe   
129961                         Sicilia      NaN  Kerin O’Keefe   
129962                         Sicilia      NaN  Kerin O’Keefe   

       taster_twitter_handle  \
0               @kerinokeefe   
6               @kerinokeefe   
13              @kerinokeefe   
22              @kerinokeefe   
24              @kerinokeefe   
...                      ...   
129929                   NaN   
129943          @kerinokeefe   
129947          @kerinokeefe   
129961          @kerinokeefe   
129962          @kerinokeefe   

                                                    title            variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)        White Blend   
6        Terre di Giurfo 2013 Belsito Frappato (Vittoria)           Frappato   
13                 Masseria Setteporte 2012 Rosso  (Etna)  Nerello Mascalese   
22      Baglio di Pianetto 2007 Ficiligno White (Sicilia)        White Blend   
24            Canicattì 2009 Aynat Nero d'Avola (Sicilia)       Nero d'Avola   
...                                                   ...                ...   
129929  Col Vetoraz Spumanti NV  Prosecco Superiore di...           Prosecco   
129943  Baglio del Cristo di Campobello 2012 Adènzia R...          Red Blend   
129947  Feudo Principi di Butera 2012 Symposio Red (Te...          Red Blend   
129961                        COS 2013 Frappato (Sicilia)           Frappato   
129962  Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...       Nero d'Avola   

                                 winery  
0

In [89]:
italian_wines = reviews[reviews.country == 'Italy']


In [91]:
reviews.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='object')

In [102]:
top_oceania_wines=reviews[(
    reviews.points>=95)&(reviews.country.isin(['Australia','Zealand'])
        
    )]

In [103]:
top_oceania_wines

Unnamed: 0    country  \
345            345  Australia   
346            346  Australia   
348            348  Australia   
349            349  Australia   
356            356  Australia   
360            360  Australia   
365            365  Australia   
14354        14354  Australia   
16538        16538  Australia   
28573        28573  Australia   
34502        34502  Australia   
34506        34506  Australia   
38988        38988  Australia   
39059        39059  Australia   
39961        39961  Australia   
39962        39962  Australia   
45809        45809  Australia   
56953        56953  Australia   
56956        56956  Australia   
56957        56957  Australia   
56959        56959  Australia   
59977        59977  Australia   
59984        59984  Australia   
67096        67096  Australia   
67101        67101  Australia   
76392        76392  Australia   
77028        77028  Australia   
77036        77036  Australia   
77037        77037  Australia   
77042        77042  Australia   
77044        77044  Australia   
77046        77046  Australia   
83357        83357  Australia   
84815        84815  Australia   
84816        84816  Australia   
87128        87128  Australia   
87137        87137  Australia   
87143        87143  Australia   
98386        98386  Australia   
99318        99318  Australia   
99330        99330  Australia   
99340        99340  Australia   
109427      109427  Australia   
109434      109434  Australia   
122421      122421  Australia   
122430      122430  Australia   
122939      122939  Australia   

                                              description  \
345     This wine contains some material over 100 year...   
346     This deep brown wine smells like a damp, mossy...   
348     Deep mahogany. Dried fig and black tea on the ...   
349     RunRig is always complex, and the 2012 doesn't...   
356     Dusty, firm, powerful: just a few apt descript...   
360     Bacon and tapenade elements merge easily on th...   
365     The Taylor family selected Clare Valley for it...   
14354   This wine's concentrated dark fruit shows in t...   
16538   Rich, dense and intense, this is a big, muscul...   
28573   Astralis has become one of Australia's top col...   
34502   This prodigious wine showcases Barossa's abili...   
34506   If Standish's Relic is the feminine side of Sh...   
38988   Penfolds Bin 707 has leapt in quality over the...   
39059   The Taylor family selected Clare Valley for it...   
39961   As unevolved as they are, the dense and multil...   
39962   Seamless luxury from stem to stern, this ‘baby...   
45809   The 2007 Astralis impresses for its combinatio...   
56953   This inky, embryonic wine deserves to be cella...   
56956   You may have to scour the country to secure so...   
56957   Thorn Clarke has taken its Shiraz to a new lev...   
56959   Is this the Yin to Grange's Yang? The wines ar...   
59977   This is a top example of the classic Australia...   
59984   This is a throwback to those brash, flavor-exu...   
67096   Just a tiny serving of this dark nectar will l...   
67101   This Muscat is the color of dark coffee, with ...   
76392   When the alcohol levels are reined in to appro...   
77028   This has all the size and weight you've come t...   
77036   RWT (unromantically derived from “Red Wine Tri...   
77037   Winemaker Dave Powell is no longer with Torbre...   
77042   This is likely the most ageworthy Shiraz winem...   
77044   The fruit for this offering comes from the Gre...   
77046   With aromas and flavors that range widely from...   
83357   A throwback to the monster Shiraz style of old...   
84815   The Factor is always one of Torbreck's biggest...   
84816   Nashwauk is Kaesler's McLaren Vale project, fi...   
87128   This full-bodied, muscular Shiraz is built for...   
87137   Perhaps the best young wine I've tasted from M...   
87143   This is wonderfully complex and aromatic, with...   
98386   One of the more approachable of the 

In [104]:
top_oceania_wines = reviews[
    (reviews.points >= 95) &
    (reviews.country.isin(['Australia', 'New Zealand']))
]
top_oceania_wines

Unnamed: 0      country  \
345            345    Australia   
346            346    Australia   
348            348    Australia   
349            349    Australia   
356            356    Australia   
360            360    Australia   
365            365    Australia   
14354        14354    Australia   
16538        16538    Australia   
28573        28573    Australia   
34502        34502    Australia   
34506        34506    Australia   
38988        38988    Australia   
39059        39059    Australia   
39961        39961    Australia   
39962        39962    Australia   
45809        45809    Australia   
56953        56953    Australia   
56956        56956    Australia   
56957        56957    Australia   
56959        56959    Australia   
59977        59977    Australia   
59984        59984    Australia   
67096        67096    Australia   
67101        67101    Australia   
76392        76392    Australia   
77028        77028    Australia   
77036        77036    Australia   
77037        77037    Australia   
77042        77042    Australia   
77044        77044    Australia   
77046        77046    Australia   
83357        83357    Australia   
84815        84815    Australia   
84816        84816    Australia   
87128        87128    Australia   
87137        87137    Australia   
87143        87143    Australia   
91851        91851  New Zealand   
98386        98386    Australia   
99318        99318    Australia   
99330        99330    Australia   
99340        99340    Australia   
109427      109427    Australia   
109434      109434    Australia   
122421      122421    Australia   
122430      122430    Australia   
122507      122507  New Zealand   
122939      122939    Australia   

                                              description  \
345     This wine contains some material over 100 year...   
346     This deep brown wine smells like a damp, mossy...   
348     Deep mahogany. Dried fig and black tea on the ...   
349     RunRig is always complex, and the 2012 doesn't...   
356     Dusty, firm, powerful: just a few apt descript...   
360     Bacon and tapenade elements merge easily on th...   
365     The Taylor family selected Clare Valley for it...   
14354   This wine's concentrated dark fruit shows in t...   
16538   Rich, dense and intense, this is a big, muscul...   
28573   Astralis has become one of Australia's top col...   
34502   This prodigious wine showcases Barossa's abili...   
34506   If Standish's Relic is the feminine side of Sh...   
38988   Penfolds Bin 707 has leapt in quality over the...   
39059   The Taylor family selected Clare Valley for it...   
39961   As unevolved as they are, the dense and multil...   
39962   Seamless luxury from stem to stern, this ‘baby...   
45809   The 2007 Astralis impresses for its combinatio...   
56953   This inky, embryonic wine deserves to be cella...   
56956   You may have to scour the country to secure so...   
56957   Thorn Clarke has taken its Shiraz to a new lev...   
56959   Is this the Yin to Grange's Yang? The wines ar...   
59977   This is a top example of the classic Australia...   
59984   This is a throwback to those brash, flavor-exu...   
67096   Just a tiny serving of this dark nectar will l...   
67101   This Muscat is the color of dark coffee, with ...   
76392   When the alcohol levels are reined in to appro...   
77028   This has all the size and weight you've come t...   
77036   RWT (unromantically derived from “Red Wine Tri...   
77037   Winemaker Dave Powell is no longer with Torbre...   
77042   This is likely the most ageworthy Shiraz winem...   
77044   The fruit for this offering comes from the Gre...   
77046   With aromas and flavors that range widely from...   
83357   A throwback to the monster Shiraz style of old...   
84815   The Factor is always one of Torbreck's biggest...   
84816   Nashwauk is Kaesler's McLaren Vale project, fi...   
87128   This full-bodied, muscular Shiraz is built for...   


In [105]:
reviews.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='object')

In [108]:
median_points=reviews['points'].median()
median_points

np.float64(88.0)

In [112]:
countries=reviews['country'].unique()
countries


array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt'], dtype=object)

In [115]:
reviews_per_country=reviews['country'].value_counts()
reviews_per_country

country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14


In [117]:
centered_price=reviews['price']-reviews['price'].mean()
centered_pricecentered_price = reviews['price'] - reviews['price'].mean()


0               NaN
1        -20.363389
2        -21.363389
3        -22.363389
4         29.636611
            ...    
129966    -7.363389
129967    39.636611
129968    -5.363389
129969    -3.363389
129970   -14.363389
Name: price, Length: 129971, dtype: float64

In [119]:
centered_price = reviews['price'] - reviews['price'].mean()
centered_price

0               NaN
1        -20.363389
2        -21.363389
3        -22.363389
4         29.636611
            ...    
129966    -7.363389
129967    39.636611
129968    -5.363389
129969    -3.363389
129970   -14.363389
Name: price, Length: 129971, dtype: float64

In [120]:
reviews.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='object')

In [121]:
reviews_written=reviews['taster_twitter_handle'].value_counts()

In [122]:
reviews_written

taster_twitter_handle
@vossroger          25514
@wineschach         15134
@kerinokeefe        10776
@vboone              9537
@paulgwine           9532
@mattkettmann        6332
@JoeCz               5147
@wawinereport        4966
@gordone_cellars     4177
@AnneInVino          3685
@laurbuzz            1835
@suskostrzewa        1085
@worldwineguys       1005
@bkfiona               27
@winewchristina         6
Name: count, dtype: int64

In [124]:
reviews.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='object')

In [ ]:
# واقف في كويز 4 رقم 2
